<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Downpour.Service-2681c0cb-2dce-4bfc-a544-eea0933d8a84</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.12" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.12" />
    <PackageReference Include="System.Management" Version="9.0.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Downpour.Core\Downpour.Core.csproj" />
    <ProjectReference Include="..\Downpour.Contracts\Downpour.Contracts.csproj" />
  </ItemGroup>
</Project>
