using Downpour.Service;

var builder = Host.CreateApplicationBuilder(args);
builder.Services.AddWindowsService(options =>
{
    options.ServiceName = "Downpour Security Monitor";
});
builder.Services.AddSingleton<SystemSnapshotProvider>();
builder.Services.AddSingleton<DriverInventoryProvider>();
builder.Services.AddSingleton<DriverPackageInventoryProvider>();
builder.Services.AddSingleton<WindowsServiceInventoryProvider>();
builder.Services.AddSingleton<InstalledSoftwareInventoryProvider>();
builder.Services.AddSingleton<NetworkInventoryProvider>();
builder.Services.AddSingleton<SecurityEventProvider>();
builder.Services.AddSingleton<SysmonProvider>();
builder.Services.AddSingleton<SecurityEventSnapshotStore>();
builder.Services.AddSingleton<SysmonSnapshotStore>();
builder.Services.AddSingleton<SecurityEventPushStatus>();
builder.Services.AddSingleton<SecurityAlertRepository>(SecurityAlertRepository.CreateForCurrentUser());
builder.Services.AddSingleton<SecurityAlertSnapshotStore>();
builder.Services.AddSingleton(OperationJournal.CreateForCurrentUser());
builder.Services.AddSingleton<QuarantineManager>();
builder.Services.AddSingleton<DriverPackageBroker>();
builder.Services.AddSingleton<HardeningPostureProvider>();
builder.Services.AddSingleton<FirewallInventoryProvider>();
builder.Services.AddSingleton(PersistenceInventoryProvider.CreateForCurrentUser());
builder.Services.AddSingleton<UsbInventoryProvider>();
builder.Services.AddSingleton<WirelessInventoryProvider>();
builder.Services.AddSingleton<RemoteAccessProvider>();
builder.Services.AddHostedService<SnapshotPipeWorker>();
builder.Services.AddHostedService<DriverInventoryPipeWorker>();
builder.Services.AddHostedService<DriverPackageInventoryPipeWorker>();
builder.Services.AddHostedService<WindowsServiceInventoryPipeWorker>();
builder.Services.AddHostedService<InstalledSoftwareInventoryPipeWorker>();
builder.Services.AddHostedService<NetworkInventoryPipeWorker>();
builder.Services.AddHostedService<SecurityEventMonitorService>();
builder.Services.AddHostedService<SecurityEventPushWorker>();
builder.Services.AddHostedService<SigmaAmsiPushWorker>();
builder.Services.AddHostedService<SysmonPushWorker>();
builder.Services.AddHostedService<SecurityEventPipeWorker>();
builder.Services.AddHostedService<SecurityAlertPipeWorker>();
builder.Services.AddHostedService<SecurityAlertControlPipeWorker>();
builder.Services.AddHostedService<OperationJournalStartupWorker>();
builder.Services.AddHostedService<ActionBrokerPipeWorker>();
builder.Services.AddHostedService<DriverPackageBrokerPipeWorker>();
builder.Services.AddHostedService<HardeningPosturePipeWorker>();
builder.Services.AddHostedService<FirewallInventoryPipeWorker>();
builder.Services.AddHostedService<PersistenceInventoryPipeWorker>();
builder.Services.AddHostedService<UsbInventoryPipeWorker>();
builder.Services.AddHostedService<WirelessInventoryPipeWorker>();
builder.Services.AddHostedService<SecurityFindingBridgeWorker>();
builder.Services.AddHostedService<RemoteAccessPipeWorker>();

var host = builder.Build();
host.Run();
