"""Extract detection constants from the v29 Python source into docs/V29_DETECTION_THRESHOLDS.md.

Every value in the output is copied from the source with its file and line, so ports can reproduce
v29 behavior without relying on summaries. Read-only against the v29 tree.

Usage: python tools/extract_v29_constants.py [v29_root]
"""
import ast
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
V29 = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(r"C:\Users\purpl\Desktop\downpour_consolidated")
MAX_LITERAL = 160
MAX_COLLECTION_ITEMS = 12


def literal(node: ast.AST) -> str | None:
    try:
        value = ast.literal_eval(node)
    except Exception:
        return None
    if isinstance(value, (list, tuple, set, frozenset)):
        items = list(value)
        text = repr(items[:MAX_COLLECTION_ITEMS])
        if len(items) > MAX_COLLECTION_ITEMS:
            text = text[:-1] + f", ... ({len(items)} items)]"
    elif isinstance(value, dict):
        keys = list(value)
        text = "{" + ", ".join(f"{k!r}: {value[k]!r}" for k in keys[:MAX_COLLECTION_ITEMS])
        text += f", ... ({len(keys)} keys)}}" if len(keys) > MAX_COLLECTION_ITEMS else "}"
    elif isinstance(value, (int, float, str, bool)) or value is None:
        text = repr(value)
    else:
        return None
    return text if len(text) <= MAX_LITERAL else text[:MAX_LITERAL] + "…"


def is_constant_name(name: str) -> bool:
    stripped = name.lstrip("_")
    return len(stripped) >= 3 and stripped.upper() == stripped and any(c.isalpha() for c in stripped)


def extract(path: Path):
    tree = ast.parse(path.read_text(encoding="utf-8", errors="ignore"))
    rows = []
    # Module- and class-level UPPER_CASE constants.
    scopes = [(None, tree.body)] + [(n.name, n.body) for n in tree.body if isinstance(n, ast.ClassDef)]
    for owner, body in scopes:
        for node in body:
            targets = []
            if isinstance(node, ast.Assign):
                targets = [t.id for t in node.targets if isinstance(t, ast.Name)]
                value = node.value
            elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.value is not None:
                targets = [node.target.id]
                value = node.value
            for name in targets:
                if is_constant_name(name) and (text := literal(value)) is not None:
                    rows.append((node.lineno, f"{owner}.{name}" if owner else name, text))
    # Numeric keyword defaults on functions whose parameter name suggests a tunable.
    tunables = ("threshold", "interval", "window", "limit", "max", "min", "ratio", "score", "timeout", "count")
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            args = node.args.args[-len(node.args.defaults):] if node.args.defaults else []
            pairs = list(zip(args, node.args.defaults)) + [
                (a, d) for a, d in zip(node.args.kwonlyargs, node.args.kw_defaults) if d is not None]
            for arg, default in pairs:
                if any(t in arg.arg.lower() for t in tunables):
                    value = literal(default)
                    if value is not None and isinstance(ast.literal_eval(default), (int, float)):
                        rows.append((node.lineno, f"{node.name}({arg.arg}=)", value))
    return sorted(set(rows))


def main():
    inventory = json.loads((REPO / "source-modules.json").read_text(encoding="utf-8"))
    modules = [m for m in inventory if m["module"].endswith(".py") and m["migrationStatus"] in ("planned", "in-progress")]
    out = [
        "# v29 detection thresholds and constants",
        "",
        "**Generated by** `tools/extract_v29_constants.py` from the v29 source tree. Do not edit by hand; re-run the script.",
        "",
        "Every row is copied from the v29 source: module- and class-level UPPER_CASE constants, plus numeric defaults of",
        "tunable-looking function parameters (threshold, interval, window, limit, ratio, score, timeout, count). Inline",
        "literals inside function bodies are **not** captured. Read the cited line before porting a detector, and add",
        "fixture tests that reproduce v29's decisions.",
        "",
        "Modules covered: `planned` and `in-progress` entries in `source-modules.json`, excluding the 61k-line main file.",
        "",
    ]
    for module in sorted(modules, key=lambda m: m["module"]):
        name = module["module"]
        if name == "downpour_v29_titanium.py":
            continue
        path = V29 / name
        if not path.exists():
            out += [f"## `{name}`", "", "_Not found in the v29 tree._", ""]
            continue
        try:
            rows = extract(path)
        except SyntaxError as error:
            out += [f"## `{name}`", "", f"_Could not parse: {error.msg} (line {error.lineno})._", ""]
            continue
        out += [f"## `{name}`", ""]
        if not rows:
            out += ["_No module-level constants or tunable defaults; thresholds, if any, are inline literals._", ""]
            continue
        out += ["| Line | Name | Value |", "|---:|---|---|"]
        out += [f"| {line} | `{label}` | `{value.replace('|', '\\|').replace('`', '´')}` |" for line, label, value in rows]
        out.append("")
    target = REPO / "docs" / "V29_DETECTION_THRESHOLDS.md"
    target.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {target} ({len(modules)} modules)")


if __name__ == "__main__":
    main()
